JohnSundell/ImagineEngine

Sources/Core/Internal/Grid.swift, Tests/ImagineEngineTests/ActorTests.swift
This patch fixes a bug that would cause an actor to be moved to an incorrect side of a block, when it has a constraint to never overlap a block in a given group.
The fix is to calculate the smallest possible delta to move the actor by, and pick that delta when moving the actor away. The result is that the actor will now snap to the most logical edge of the block instead of being moved to another one of the block’s sides.
=> Actor: Pick smallest delta when moving away from block

Sources/Core/API/Actor.swift, Sources/Core/API/Animation.swift, Tests/ImagineEngineTests/ActorTests.swift
This change makes actors render their initial animation frame directly when the animation is assigned, rather than waiting for the next screen update. The reason for this is to enable the actor’s size to be set as soon as it’s added to a scene, to enable easier positioning.
This also enables an optimization path in that an animation action does not have to be added in case only a single frame is being rendered.
This change also includes a new convenience API to create an animation from an array of images, which enables more thorough testing of the resizing feature.
=> Actor: Render first animation frame directly

Sources/Core/Internal/DisplayLink-macOS.swift
CVDisplayLink gets called on a background thread, to maintain consistency with iOS we dispatch the game’s callback on the main queue.
=> Mac: Run game on the main thread

Sources/Core/API/Actor.swift, Tests/ImagineEngineTests/ActorTests.swift
`CALayer` can get some funky values as its rect when not displayed on the screen yet on macOS. To make things nice and consistent we now compute an actor’s rect manually whenever the position or size changes.
=> Actor: Compute rect manually

ImagineEngine.xcodeproj/project.pbxproj, Sources/Core/API/Actor.swift, Sources/Core/API/Animation.swift, Sources/Core/API/AnimationAction.swift, Sources/Core/API/SpriteSheet.swift, Tests/ImagineEngineTests/ActorTests.swift
This change adds support for using a single sprite sheet texture for an animation, that lets an actor animate over sub-rectangles of that texture, which can contain a single or multiple rows.
This new feature is a compliment to the already existing option of using separate image files for each texture. The advantage of using a sprite sheet is that only a single image needs to be loaded into memory, and drawing can be done by simply offsetting that single texture instead of having to draw a completely new one.
This change very slightly breaks the existing `Animation` API in that an array of textures need to be wrapped in a `.textures` enum case if assigned directly to an existing animation.
=> Add support for sprite sheet-based animations

ImagineEngine.xcodeproj/project.pbxproj, Sources/Core/API/TextureManager.swift, Tests/ImagineEngineTests/TextureManagerTests.swift
Achieved by adding recursion call with a stop condition.
Note, that I'm not addressing [the comment](https://github.com/JohnSundell/ImagineEngine/issues/11#issuecomment-339160493) about optimisation here. Let's maybe have a separate issue for that?
=> Implement fallback to lower scale textures if exact match can't be found

Documentation/Tutorials/1-AsteroidBlaster/FinalCode.swift, Documentation/Tutorials/1-AsteroidBlaster/README.md
This changes the asteroid creation interval in the “Asteroid Blaster” tutorial to 2 seconds. This to give the asteroids enough space in between as to not have their frames overlap, which could enable the player to destroy 2 asteroids with one tap.
Resolves https://github.com/JohnSundell/ImagineEngine/issues/10
=> Asteroid Blaster tutorial: Create an asteroid every 2 seconds

ImagineEngine.xcodeproj/project.pbxproj, Sources/Core/API/Camera.swift, Sources/Core/Internal/ClickGestureRecognizer-macOS.swift, Sources/Core/Internal/ClickPlugin.swift, Tests/ImagineEngineTests/CameraTests.swift, Tests/ImagineEngineTests/Mocks/ClickGestureRecognizerMock.swift, Tests/ImagineEngineTests/Mocks/GameMock.swift, Tests/ImagineEngineTests/SceneTests.swift
This patch fixes 2 bugs when it comes to what point is passed into a scene’s click event handler:
1. On macOS, an incorrect y coordinate was passed, since macOS uses a bottom-left anchored coordinate system.
2. When a scene’s camera was moved, the camera’s position wasn’t taken into account when computing the clicked point.
This change also adds a `rect` property to `Camera`, which is being used in the fix.
=> Scene: Adjust click points for macOS + camera position

Sources/Core/API/Actor.swift, Sources/Core/API/ActorEventCollection.swift, Tests/ImagineEngineTests/ActorTests.swift
This new event will be triggered right before an actor is moved, and contains the new position that the actor will be moved to.
=> Actor: Add ‘willMove’ event

Sources/Core/API/Animation.swift, Tests/ImagineEngineTests/ActorTests.swift
This patch fixes a bug that would prevent an actor from updating a sprite sheet based animation, since it didn’t get an identifier assigned.
=> Animation: Fix missing identifier when using a sprite sheet

ImagineEngine.xcodeproj/project.pbxproj, Sources/Core/API/Timeline.swift, Sources/Core/Internal/ActionWrapper.swift, Sources/Core/Internal/UpdatableCollection.swift, Sources/Core/Internal/UpdatableWrapper.swift, Tests/ImagineEngineTests/ActionTests.swift
This patch fixes a race condition that could cause a chained action not to be performed when multiple ones were chained together. The problem had two parts to it:
1. An action could be started even though it was pending or cancelled.
2. `Timeline` wouldn’t keep its updatables in order, and instead use a `Set`. This was fixed by introducing a custom collection wrapper that maintains the order of the updatables.
=> Action: Fix race condition when chaining multiple actions

Sources/Core/API/Camera.swift, Sources/Core/API/Scene.swift, Tests/ImagineEngineTests/CameraTests.swift
This change adds a new property on camera that lets it be constrained to its scene, meaning that it can not move outside of it. The default is false, which matches the current behavior.
=> Camera: Enable constraining to scene

Sources/Core/API/Actor.swift, Sources/Core/API/ActorEventCollection.swift, Tests/ImagineEngineTests/ActorTests.swift, Tests/ImagineEngineTests/EventTests.swift
This fix merges the previously introduced `willMove` event into the `move` event and makes it include a tuple with both the old and new positions as its value. This enables logic that uses either the old or new position to use the exact same event.
Further, a fix has been made to not send duplicate events when a position is corrected by, for example, constraints. Only the final position is now emitted as an event, if it differs from the original.
=> Actor: Combine move events & remove duplicates

ImagineEngine.xcodeproj/project.pbxproj, Sources/Core/API/TextureImageLoader.swift, Sources/Core/API/TextureManager.swift, Sources/Core/Internal/BundleImageLoader.swift, Sources/Core/Internal/BundleTextureImageLoader.swift, Tests/ImagineEngineTests/ActorTests.swift, Tests/ImagineEngineTests/Mocks/TextureImageLoaderMock.swift, Tests/ImagineEngineTests/TextureManagerTests.swift, Tests/ImagineEngineTests/Utilities/ImageMockFactory.swift
This PR resolves #16.
The main idea here is to cache images without adding scale to the cache key.
Another thing is to move `scale` param right into `TextureImageLoader` protocol method, because different image loading pipelines may have different ways of obtaining correct scales of the image (and it feels right to move this logic out of `TextureManager`).
Also provided couple more refactorings around `TextureManager`: extracted bundle image loading to `BundleImageLoader` that conforms to `TextureImageLoader` protocol.
=> Implement remembering texture scale fallbacks

ImagineEngine.xcodeproj/project.pbxproj, ImagineEngine.xcodeproj/xcshareddata/xcschemes/ImagineEngine-tvOS.xcscheme, Sources/Core/API/Label.swift, Sources/Core/Internal/Font+Default.swift, Sources/Integrations/UIKit/GameViewController-iOS+tvOS.swift, buddybuild_postbuild.sh
This change makes Imagine Engine compile and all tests pass on tvOS. The following changes were required:
- Add tvOS targets & scheme.
- tvOS does not have `UIFont.systemFontSize`, so a category on `Font` was created to provide an internal cross-platform API.
- `GameViewController.swift` was renamed to `GameViewController-iOS+tvOS.swift`.
- Only override `prefersStatusBarHidden` for iOS.
=> Add support for tvOS

Sources/Core/API/ActorEventCollection.swift, Sources/Core/API/SceneEventCollection.swift, Sources/Core/Internal/DisplayLink-iOS+tvOS.swift
A simple change to remove type annotations and `self` references from lazy property declarations, since they are no longer required in Swift 4.
=> Modernize lazy var declarations

ImagineEngine.xcodeproj/project.pbxproj, Sources/Core/API/Game.swift, Sources/Core/API/Scene.swift, Sources/Core/API/SceneEventCollection.swift, Sources/Core/API/Typealiases.swift, Sources/Core/Internal/DisplayLinkProtocol.swift, Sources/Core/Internal/EdgeInsets-macOS.swift, Sources/Core/Internal/GameView.swift, Tests/ImagineEngineTests/Mocks/GameMock.swift, Tests/ImagineEngineTests/Mocks/GameViewMock.swift, Tests/ImagineEngineTests/SceneTests.swift
Similar to how UIKit now includes a `safeAreaInsets` API to be able to easily place UI elements away from the notch & home indicator on iPhone X.
Changes required:
- Add `safeAreaInsets` property on `Scene`, note that it’s not only available
on iOS, but on all platforms - preserving the cross platformness of Imagine.
- Add `safeAreaInsetsChanged` event on `SceneEventCollection` that gets triggered
when the safe area insets were changed.
- Make it possible to inject a mocked `GameView` in `Game`, to enable unit testing
of this new feature.
- Make a cross-platform type alias of `NS/UIEdgeInsets = EdgeInsets`.
Here's the new API in use in the start screen of Revazendo, to position the version & copyright labels 😄
=> Scene: Add safe area insets API

ImagineEngine.xcodeproj/project.pbxproj, Sources/Core/API/Actor.swift, Sources/Core/API/Camera.swift, Sources/Core/API/Pluggable.swift, Sources/Core/API/Scene.swift, Sources/Core/Internal/PluginManager.swift, Sources/Core/Internal/PluginWrapper.swift, Tests/ImagineEngineTests/SceneTests.swift
This change makes all APIs that add plugins to either an actor, camera or scene return either that instance or any existing plugin instance of the same type.
Since all plugin add methods accept an auto closure, no new instance needs to be created in case an existing one already exists. This enables nice extension APIs to be written on top of Imagine Engine.
For example, here's how an audio engine could be integrated into Imagine Engine to provide a way for an actor to play a sound effect:
```swift
extension Actor {
private var audioPlugin { return add(AudioPlugin()) }
func playSound(named name: String) {
audioPlugin.playSound(named: name)
}
}
```
=> Plugins: Return existing instance when adding a plugin

Sources/Core/API/Actor.swift, Sources/Core/API/Animation.swift, Tests/ImagineEngineTests/ActorTests.swift
This change makes it possible to initialize an actor with just a texture name, which is very common for single-image actors. It also adds a `scale` parameter to the `Animation` initializer that takes a texture name.
=> Actor/Animation: Add convenience initializer that takes a texture name

Sources/Core/API/TextureManager.swift, Tests/ImagineEngineTests/TextureManagerTests.swift
This change adds a `namePrefix` property on `TextureManager`, that can be used to assign a prefix to all textures loaded by that manager. This is super useful when all graphics for a game are contained in a single folder, and lets you skip referring to that folder every time you reference a texture.
=> TextureManager: Add support for assigning a scene-wide name prefix

Sources/Core/API/Actor.swift, Tests/ImagineEngineTests/ActorTests.swift
This change makes an actor’s rect adapt according to its scale. Otherwise an actor’s `rect` property doesn’t match the actual pixels its being rendered on.
=> Actor: Adapt rect according to scale

Sources/Core/API/Actor.swift
This change removes the use of `defer` to trigger a property’s `didSet` observation. While this currently works, it has been confirmed to be because of a compiler bug that will will be fixed soon.
Instead of relying on defer, the methods dealing with changes in values are now explicitly called during init instead.
=> Actor: Remove use of defer to trigger property observers

Sources/Core/API/RepeatAction.swift, Tests/ImagineEngineTests/ActionTests.swift
This change adds a simple convenience API on all action performs to enable an action to be repeated until its cancelled.
=> ActionPerformer: Add convenience API to repeat an action

Sources/Core/API/Actor.swift, Sources/Core/API/Camera.swift, Sources/Core/API/Pluggable.swift, Sources/Core/API/Scene.swift, Sources/Core/Internal/PluginManager.swift, Tests/ImagineEngineTests/SceneTests.swift
This change adds an API on `Pluggable` for removing all plugins of a certain type. This is very useful in situations where you don’t want to keep a reference to a certain plugin in order to be able to remove it.
=> Plugins: Add API for removing all plugins of a type

ImagineEngine.xcodeproj/project.pbxproj, Sources/Core/API/Actor.swift, Sources/Core/API/Block.swift, Sources/Core/API/Label.swift, Sources/Core/API/Scene.swift, Sources/Core/API/ZIndexed.swift, Sources/Core/Internal/Grid.swift
This change is the first in a series of changes aimed to reduce the code duplication between Actor, Block and Label. Starting with managing z indexes, which has now been moved to a new `ZIndexed` protocol.
=> Add ZIndexed protocol and use it to reduce z-index code duplication

ImagineEngine.xcodeproj/project.pbxproj, Sources/Core/API/Actor.swift, Sources/Core/API/Block.swift, Sources/Core/API/Label.swift, Sources/Core/API/Scene.swift, Sources/Core/Internal/SceneObject.swift, Tests/ImagineEngineTests/ActorTests.swift, Tests/ImagineEngineTests/BlockTests.swift, Tests/ImagineEngineTests/LabelTests.swift
This change introduces a `SceneObject` protocol that Actor, Block and Label conform to, in order to be able to use the same code path for deactivating objects when removed.
=> Add SceneObject protocol and use it to reduce deactivation code duplication

Sources/Core/API/Scene.swift, Tests/ImagineEngineTests/SceneTests.swift
No need to go through the Grid, as it’s about to be reset as well. This change also adds some more verification to the test for the reset operation.
=> Scene: Deactivate objects directly when resetting

Sources/Core/API/Scene.swift, Tests/ImagineEngineTests/Mocks/PluginMock.swift, Tests/ImagineEngineTests/SceneTests.swift
When resetting a scene, we don’t want to remove its plugins, but we do want them to be deactivated and then re-activated. This because some plugins observe events on its scene, and those events get removed as part of a reset.
=> Scene: Toggle plugin activation when reset

Sources/Core/API/Scene.swift
Now that we have a black color as the default, we need to call `backgroundColorDidChange()` in init in order to get it to be rendered by the layer.
=> Scene: Render initial background color

Sources/Core/API/Timeline.swift, Sources/Core/Internal/ClosureUpdatable.swift, Tests/ImagineEngineTests/TimelineTests.swift
This change makes it possible to pass any object into a timeline closure to have it automatically weak-reference it. If the object is deallocated, then the timeline will discard the event and associated closure.
**This enables you to replace this:**
```swift
timeline.repeat(withInterval: 5) { [weak self] in
self?.doSomething()
}
```
**with this:**
```swift
timeline.repeat(withInterval: 5, using: self) { scene in
scene.doSomething()
}
```
It also has the added benefit of automatically cancelling any timeline event if the associated object is deallocated.
=> Timeline: Support passing a weak-referenced object to closures

Sources/Core/API/ActionToken.swift, Tests/ImagineEngineTests/ActionTests.swift
Similar to the recent change to enable an object to be passed into a timeline closure, with this change it’s now possible to pass any object into an action’s completion handler and have it automatically be weak referenced - eliminating the need to do `[weak self] in`.
=> ActionToken: Support passing a weak-referenced object to ‘then’ closure

Sources/Core/Internal/Grid.swift, Tests/ImagineEngineTests/ActorTests.swift
Now we use the actor's ```rect```, instead of actor's ```size```, because the ```rect``` is already adjusted for its scale.
=> Grid: taking an actor's scale into account when evaluating actor scene constraint

Dangerfile, Gemfile, buddybuild_finally.sh, buddybuild_postbuild.sh
This change adds Danger to the CI process, to show linting warnings inline and whether a PR is too big or lacks a description.
For now this uses the standard Ruby version of Danger, but we should totally use Danger-Swift & Marathon in the future.
=> CI: Add Danger

.swiftlint.yml, Documentation/Tutorials/2-Walkabout/FinalCode.swift, Sources/Core/API/Action.swift, Sources/Core/API/Actor.swift, Sources/Core/API/Animation.swift, Sources/Core/API/Block.swift, Sources/Core/API/EventCollection.swift, Sources/Core/API/Game.swift, Sources/Core/API/MoveAction.swift, Sources/Core/API/Pluggable.swift, Sources/Core/API/Scene.swift, Sources/Core/API/TextureManager.swift, Sources/Core/API/Timeline.swift, Sources/Core/Internal/DisplayLink-macOS.swift, Sources/Core/Internal/EdgeInsets-macOS.swift, Sources/Core/Internal/Image-macOS.swift, Sources/Core/Internal/PluginManager.swift, Sources/Integrations/AppKit/GameViewController-macOS.swift, Sources/Integrations/AppKit/GameWindowController.swift, Sources/Integrations/UIKit/GameWindow.swift, Tests/ImagineEngineTests/ActorTests.swift, Tests/ImagineEngineTests/BundleTextureImageLoaderTests.swift, Tests/ImagineEngineTests/Utilities/Assert.swift
A lot of SwiftLint rules have now been enabled. They were initially disabled to enable SwiftLint integration, but now it’s time to enable them and fix all warnings and errors that they result in.
Most fixes are removal of whitespace and shortening of lines, and at some places local disabling of rules had to be inserted (when force casting has to be used).
=> SwiftLint: Enable most rules + fix codebase to match

Gemfile, buddybuild_postbuild.sh
By default, xcodebuild generates a “wall of text” as its output, so let’s use xcpretty to make it a lot more readable. The build commands have now also been split up on multiple lines to make them easier to read.
=> CI: Use xcpretty to format xcodebuild output

buddybuild_postbuild.sh
To enable the build to fail when a macOS or tvOS test fails.
=> CI: Use xcpretty with pipefail

Dangerfile
This change introduces two new Danger warnings, one if a PR includes merge commits (which we want to avoid in order to get a somewhat clean Git history), and one in case the `Sources/` folder has been modified, but the `Tests/` folder hasn’t. Note that none of these prevent a merge, they’re just friendly suggestions.
=> CI: Add Danger warnings for merge commits & missing tests

Sources/Core/API/EventCollection.swift, Tests/ImagineEngineTests/EventTests.swift
Currently, it’s only possible to make custom events with a subject type if you also have a subject identifier. While this works for cases where you want to make the observation conditional on the subject, for events that only pass a subject when observed this is not sufficient. This change fixes this by allowing any subject type to be used with a custom event.
(Tests initially omitted to test the new Danger warning)
=> EventCollection: Enable custom events to be created with a subject type

Tests/ImagineEngineTests/ActorTests.swift
This fixes an issue where these tests don't pass when running on a retina display because the actor size is scaled during the animations, but the original images are not.
Although this may not be the ideal solution, having tests breaking out of a clean branch may be confusing to new contributors, so I think it leaves us in a better shape for now.
=> Uses scaled images on tests

Sources/Core/API/Actor.swift, Sources/Core/API/Block.swift, Sources/Core/API/Label.swift, Sources/Core/API/Scene.swift, Sources/Core/Internal/SceneObject.swift
`SceneObject`s are now responsible for adding themselves to the scene layer.
This change is needed to support new types of scene objects that uses custom layers. See issue #85
=> Added new function addLayer to SceneObject

Sources/Core/API/Timeline.swift, Sources/Core/Internal/ClosureUpdatable.swift, Tests/ImagineEngineTests/TimelineTests.swift
This change makes it possible to pass a `RepeatMode` when starting to repeat a closure with a given time interval. This is very useful for situations when you want to repeat something only a few times without having to manually manage a token for it.
=> Timeline: Enable setting a repeat mode when using the repeat API

Sources/Core/API/Actor.swift, Sources/Core/API/ActorEventCollection.swift, Sources/Core/API/Block.swift, Sources/Core/Internal/Grid.swift, Tests/ImagineEngineTests/ActorTests.swift
This change introduces several optimizations in how collision detection is performed for both actors and blocks, in order to avoid duplicate or unnecessary operations.
- Activate an object’s collision detection lazily, whenever a collision event is first accessed.
- Remove collision events that target any actor or any block. These make it hard to perform optimizations, and are very unlikely to be used in any real-life game development.
- Keep track of whenever a block and actor is in contact, to avoid handling duplicate collisions.
- Don’t perform collision detection unless someone’s interested in it, and in case we only need to do collision detection to evaluate constraints, there’s now an optimization path for that.
With this change, adding 100 objects on the same point in a scene is …
=> Collision detection: Activate lazily, make more thorough & remove 'any' events

Sources/Core/API/Timeline.swift, Sources/Core/Internal/UpdatableCollection.swift, Tests/ImagineEngineTests/TimelineTests.swift
This patch makes `Timeline` handle large amounts of updates a lot better, by reducing the need for performing mutations on value types.
Currently, whenever a frame is rendered, `Timeline` removes all of its updatables from `UpdatableCollection`, updates them and then re-adds them to the collection. This gives us a lot of unncesseceray value mutations.
On top of that we were using `Set` and `Array` to store updatables, both by identity and by index. This required more memory than neccessary, and made mutations more expensive, since many times the underlying buffers needed to be copied, destroyed or re-created.
With this patch, we are now storing updatables using linked lists instead, which, in combination with a lightweight dictionary index gives us both quick inserts and deletions. We …
=> Timeline: Improve performance by reducing needs for mutations

ImagineEngine.xcodeproj/project.pbxproj, Sources/Core/API/Camera.swift, Sources/Core/API/CameraEventCollection.swift, Tests/ImagineEngineTests/CameraTests.swift
This PR introduces  new `CameraEventsCollection` along with `moved` event to observe changes in camera`s position. 
Linked issue #86
=> Camera: add moved event to observe changes in position of camera

Sources/Core/API/Scene.swift, Sources/Core/API/SceneEventCollection.swift, Tests/ImagineEngineTests/SceneTests.swift
This change introduces two new events for `Scene`; `actorAdded` & `actorRemoved`. This enables observation of when an actor is added or removed from a scene.
Resolves https://github.com/JohnSundell/ImagineEngine/issues/68
=> Scene: Add events for when an actor is added or removed

Documentation/Tutorials/1-AsteroidBlaster/FinalCode.swift, Documentation/Tutorials/1-AsteroidBlaster/README.md
The asteroid blaster tutorial was using the now deleted `collidedWithAnyBlock` event, so this patch updates it to now use `collided(withBlockInGroup:)` instead.
=> Asteroid blaster tutorial: Update for removed any block event

Sources/Core/API/Animation.swift
Since the y-axis is flipped on macOS compared to iOS the animation for a multiline sprite sheet will start from the bottom row instead of the top row. This PR fixes the issue.
=> Animation: Fixed bug when using mulitline sprite sheets on macOS.

ImagineEngine.xcodeproj/project.pbxproj, Sources/Core/API/TextureManager.swift, Sources/Core/Internal/TextureErrorHandler.swift, Tests/ImagineEngineTests/Mocks/TextureErrorHandlerMock.swift, Tests/ImagineEngineTests/TextureManagerTests.swift
Issue number: #61 
@JohnSundell Could you throw some light on how this could be tested? Considering that the scenarios to be tested would be 
- Ensure there is no action when `IgnoreError` is selected
- Ensure there is logging when `LogError` is selected
- Ensure there is assert when `TriggerAssertOnError` is selected
I am not entirely confident of the changes without the tests.
=> Adds errorMode to TextureManager for Debug Mode.

Sources/Core/API/Actor.swift, Sources/Core/API/ActorEventCollection.swift, Tests/ImagineEngineTests/ActorTests.swift
Event for when rotation changes is useful for example when you want the rotation of two actors to be synchronized.
=> Actor: Added rotated event

ImagineEngine.xcodeproj/project.pbxproj, Sources/Core/API/Actor.swift, Sources/Core/API/Shadow.swift, Sources/Core/API/Typealiases.swift, Tests/ImagineEngineTests/ActorTests.swift
This change adds support for assigning a shadow to an actor, which in turn will be assigned to the underlying `CALayer`.
This enables cool effects like this shadow in Revazendo when the ship acquires the new Speed Up powerup:
=> Actor: Add support for shadows

Sources/Core/Internal/Grid.swift, Tests/ImagineEngineTests/ActorTests.swift
This patch fixes a bug that would cause an actor that belongs to a group to always participate in collisions, even if collision detection had been disabled.
=> Grid: Fix bug causing actors in groups always participating in collisions

Sources/Core/API/Label.swift, Tests/ImagineEngineTests/LabelTests.swift
This change adds a new API for `Label` that lets the user set a horizontal alignment mode. This naming makes it possible to also introduce a vertical alignment mode in the future.
=> Label: Add API for setting a horizontal alignment mode

Sources/Core/API/Animation.swift, Tests/ImagineEngineTests/ActorTests.swift
This change makes it possible to form an animation for an Actor using JPG textures. This was already possible using explicit images or with a single texture, but it’s now also possible when referring to an animation by name.
=> Animation: Support animating with JPG textures

Sources/Core/API/Label.swift, Tests/ImagineEngineTests/LabelTests.swift
This change makes it possible to add plugins to a Label instance. It works the same way as for Scene, Camera and Actor.
=> Label: Add support for plugins

.travis.yml, CI.sh
Since Buddybuild was just acquired by Apple they will stop supporting open source projects from the 1st of March. This change makes Imagine Engine start using Travis CI instead for its CI needs.
=> CI: Migrate from Buddybuild to Travis CI

ImagineEngine.xcodeproj/project.pbxproj, Sources/Core/API/Actor.swift, Sources/Core/API/ActorEventCollection.swift, Sources/Core/API/Block.swift, Sources/Core/API/Label.swift, Sources/Core/API/LabelEventCollection.swift, Sources/Core/API/Scene.swift, Sources/Core/Internal/ClickPlugin.swift, Sources/Core/Internal/Grid.swift, Sources/Core/Internal/SceneObject.swift, Tests/ImagineEngineTests/ActorTests.swift, Tests/ImagineEngineTests/LabelTests.swift, Tests/ImagineEngineTests/Mocks/GameMock.swift, Tests/ImagineEngineTests/SceneTests.swift
This change makes it possible to observe clicks on labels. The opportunity to remove some code duplication between scene objects was also taken, so that each scene object is now responsible for its own grid tile management.
Also, since we now have two clickable objects - `Actor` and `Label`, click management has been simplified so that a scene always adds a `ClickPlugin` instead of doing it lazily. This should lead to some minor performance gains as checks can be removed whenever a click event is observed.
=> Label: Add support for observing clicks

Sources/Core/API/Block.swift
Convenient, so that you don’t have to create a full texture collection just to use a single texture.
=> Block: Add convenience initializer that takes a single texture

Sources/Core/Internal/Grid.swift, Tests/ImagineEngineTests/SceneTests.swift
This patch fixes a bug that could cause actors or labels to be incorrectly returned when asking for objects at a certain point. The problem was that all members of the grid tile in question would be returned. Now, we always check that an object’s rect contains the given point.
=> Scene: Fix actors/labels incorrectly returned for a given point

Sources/Core/API/Scene.swift, Sources/Core/Internal/Grid.swift
This is a refactor in preparation of an upcoming change that will enable scene objects to be added to a `Camera`, as well as to a `Scene`. In order to avoid code duplication, the goal is to move more object management responsibilities into the `Grid` class, starting with activation & deactivation.
=> Grid: Handle activation & deactivation

Sources/Core/API/Scene.swift, Sources/Core/API/SceneEventCollection.swift, Tests/ImagineEngineTests/SceneTests.swift
This new event will be triggered whenever a scene was resized. Also contains a small cleanup after always adding `ClickPlugin` to all scenes.
=> Scene: Add resized event

Sources/Core/API/Camera.swift, Sources/Core/API/Scene.swift
This change makes `Camera` observe whenever its scene is resized to update itself, rather than relying on `Scene` setting a property on it.
=> Camera: Use scene resize event instead of custom property

Sources/Core/API/Actor.swift, Sources/Core/API/Block.swift, Sources/Core/API/Label.swift, Sources/Core/API/Scene.swift, Sources/Core/Internal/Grid.swift
This change refactors the way scene objects are deactivated and removed from a scene. Currently, the concepts of deactivation and removal are a bit entangled, so this change clears that up a bit.
- Deactivation: The object is no longer active in a scene, either because it was removed, or because the scene itself was deactivated.
- Removal: The object and its layer are removed from the scene.
To make this happen, `Grid` is now responsible for all deactivation, including when the scene is reset or when an object is removed.
To increase predictability, the only way to remove scene objects are now by calling `remove()` on the object itself, rather than being able to use an API on `Scene`.
=> Refactor deactivation code to make it more predictable

Sources/Core/API/Camera.swift, Sources/Core/API/CameraEventCollection.swift, Sources/Core/API/Scene.swift, Sources/Core/Internal/ClickPlugin.swift, Sources/Core/Internal/Grid.swift, Tests/ImagineEngineTests/CameraTests.swift
With this change `Camera` now has a `clicked` event that can be used to observe clicks within the camera’s coordinate space. This change also includes a refactor to make the click handling handled more by the individual objects and by `Grid`, to make it easier to add more click features in the future.
=> Camera: Add ‘clicked’ event

Sources/Core/API/Scene.swift, Sources/Core/Internal/Grid.swift
This change makes `Grid` handle the activation of scene objects when they are added to a scene. This to support the upcoming feature of being able to add scene objects directly to the camera.
=> Grid: Handle activation of scene objects when added

Sources/Core/API/Scene.swift, Tests/ImagineEngineTests/SceneTests.swift
This patch fixes a recent regression that would prevent a scene’s grid from being reactivated after a reset. This manifested itself by actions not running after a reset, so that’s what I used to reproduce the bug & verify the fix in a test.
=> Scene: Re-activate grid after reset

Sources/Core/API/Actor.swift
Enable applying a corner radius to an actor, which in turn sets the corner radius of the actor’s backing layer.
=> Actor: Enable setting a corner radius

Sources/Core/API/Label.swift, Tests/ImagineEngineTests/LabelTests.swift
Created a public property to enable multiple lines using CATextLayer's isWrapped.
=> Multiple lines support for Label

Sources/Core/API/Actor.swift, Tests/ImagineEngineTests/ActorTests.swift
This PR adds the API methods requested in https://github.com/JohnSundell/ImagineEngine/issues/109 for knowing if one Actor is in contact with another actor or a Block.
=> add isInContact API methods for an Actor.

ImagineEngine.xcodeproj/project.pbxproj, Sources/Core/API/Animation.swift, Sources/Core/API/Coordinate.swift, Sources/Core/API/SpriteSheet.swift, Tests/ImagineEngineTests/SpriteSheetTests.swift
This change makes it possible to slice a sprite sheet up for animation purposes. This enables the API user to use sprite sheet as atlases, with many animations baked into the same sprite sheet.
Using a new slicing API on `SpriteSheet` combined with a new `Coordinate` structure, you can now easily reference a “slice” of a sprite sheet when creating an animation.
When implementing this, the frame calculation code for sprite sheets was moved from `Animation` into `SpriteSheet` itself.
Here's the new API in action, used to animate a `player` and an `enemy` using frames from the same sprite sheet:
```swift
let sprites = SpriteSheet(textureNamed: "sprites", frameCount: 10)
let player = Actor()
player.animation = Animation(
spriteSheet: sprites.slice(from: .zero...Coordinate(x: 4, y: 0)), …
```
=> Introduce sprite sheet slicing

Sources/Core/API/SpriteSheet.swift, Tests/ImagineEngineTests/SpriteSheetTests.swift
This change adds a convenience initializer to `SpriteSheet` that makes it easy to create an instance by just entering the number of rows and columns of a sprite sheet rather than having to calculate the exact frame count (we have computers for that! 😉)
=> SpriteSheet: Add convenience API for initializing with a column/row count

ImagineEngine.xcodeproj/project.pbxproj, Sources/Core/API/Actor.swift, Sources/Core/API/Label.swift, Sources/Core/Internal/CALayer+Transform.swift, Sources/Core/Internal/Layer.swift, Sources/Core/Internal/TextLayer.swift, Tests/ImagineEngineTests/ActorTests.swift, Tests/ImagineEngineTests/LabelTests.swift, Tests/ImagineEngineTests/Utilities/XCTAssertEqual+CATransform3D.swift
This change refactors the layer transformation code from being concrete implementations on `Layer` and `TextLayer` to be a more generalized extension on any `CALayer`. This to enable more `CALayer` subclasses to easily be introduced, and to be able to reduce code duplication.
=> Generalize layer transformation code

Sources/Core/API/Actor.swift, Sources/Core/API/Block.swift, Sources/Core/Internal/Grid.swift, Tests/ImagineEngineTests/ActorTests.swift
This changes the way contacts are managed between actors and blocks, and pushes the responsibility of managing object contacts back to `Grid`, instead of being handled in each separate object.
The new implementation is more robust, since it invalidates contacts on each rect change, rather than just when an object moves between different grid tiles. It also now treats edge-to-edge contacts (that is, no overlap but a distance of 1 pixel or less between two objects) as a contact. This is really useful in platform games, when you want to check if the player is currently standing on the ground, for example.
=> Actor: Rework contact management to support edge-to-edge contacts

Sources/Core/API/Animation.swift
When creating an animation, a specific texture scale can now be used when automatically creating an animation from a series of textures.
=> Animation: Support specifying a texture scale

.travis.yml, ImagineEngine.xcodeproj/project.pbxproj, ImagineEngine.xcodeproj/xcshareddata/xcschemes/ImagineEngine-iOS.xcscheme, ImagineEngine.xcodeproj/xcshareddata/xcschemes/ImagineEngine-macOS.xcscheme, ImagineEngine.xcodeproj/xcshareddata/xcschemes/ImagineEngine-tvOS.xcscheme, Sources/Core/API/InstanceHashable.swift, Sources/Core/API/Pluggable.swift, Tests/ImagineEngineTests/Utilities/Assert.swift
This update enables the source to compile as Swift 5. The test suites all still pass, and no changes to the user-visible API have been made.
=> Updating Hashable support to Swift 5 format on InstanceHashable.swift
